repos:
  # Code formatting
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
        language_version: python3.12

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Check yaml files
      - id: check-yaml

      # Check file size
      - id: check-added-large-files

      # Check python syntax validation
      - id: check-ast

      # Prevent commiting unresolved merge confliccts
      - id: check-merge-conflict

      # Ensure files end with a newline
      - id: end-of-file-fixer

      # Remove trailing whitespace
      - id: trailing-whitespace

      # Prevent commiting .env files
      - id: forbid-new-submodules
      - id: detect-private-key

  # Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.2
    hooks:
      - id: mypy
        additional_dependencies: [pandas]
